version: '3.7'

services:
  node:
    image: node:14.3.0
    restart: always
    stdin_open: true
    ports:
      - 7900:3000
    volumes:
      - .:/client
      - hidden_node_modules:/client/node_modules
    command: bash -c "cd client && yarn install && yarn start"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
volumes:
  hidden_node_modules:
